using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Prism.SourceGenerators.Diagnostics;
using Prism.SourceGenerators.Helpers;
using Prism.SourceGenerators.Models;

namespace Prism.SourceGenerators;

/// <summary>
/// A source generator that generates <c>INotifyPropertyChanged</c> implementation for classes annotated
/// with <c>[BindableBase]</c> that do not already inherit from <c>Prism.Mvvm.BindableBase</c>.
/// <para>
/// Generates: <c>PropertyChanged</c> event, <c>SetProperty</c>, <c>RaisePropertyChanged</c>,
/// and <c>OnPropertyChanged</c> methods.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BindableBaseGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Prism.SourceGenerators.BindableBaseAttribute";
    private const string BindableBaseFullName = "Prism.Mvvm.BindableBase";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("BindableBaseAttribute.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace Prism.SourceGenerators;

                /// <summary>
                /// An attribute that can be applied to a class to generate an <c>INotifyPropertyChanged</c>
                /// implementation when the class does not inherit from <c>Prism.Mvvm.BindableBase</c>.
                /// <para>
                /// The generated code includes:
                /// <list type="bullet">
                /// <item><c>PropertyChanged</c> event</item>
                /// <item><c>SetProperty&lt;T&gt;</c> method for updating backing fields with change notification</item>
                /// <item><c>RaisePropertyChanged</c> method for manually raising <c>PropertyChanged</c></item>
                /// <item><c>OnPropertyChanged</c> virtual method for subclass customization</item>
                /// </list>
                /// </para>
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                [global::System.Diagnostics.Conditional("PRISM_SOURCEGENERATORS_ATTRIBUTES")]
                internal sealed class BindableBaseAttribute : global::System.Attribute
                {
                }
                """);
        });

        IncrementalValuesProvider<Result<HierarchyInfo>> classInfos =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeName,
                    static (node, _) => node is ClassDeclarationSyntax,
                    static (context, token) => ExtractClassInfo(context, token));

        // Report diagnostics
        context.RegisterSourceOutput(
            classInfos.Where(static item => !item.Errors.IsEmpty),
            static (context, result) =>
            {
                foreach (DiagnosticInfo diagnostic in result.Errors.AsImmutableArray())
                {
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());
                }
            });

        // Generate source
        context.RegisterSourceOutput(
            classInfos
                .Where(static item => item.Value is not null && !item.HasBlockingDiagnostics)
                .Select(static (item, _) => item.Value!),
            static (context, hierarchy) =>
            {
                string source = GenerateBindableBaseSource(hierarchy);
                context.AddSource($"{hierarchy.FilenameHint}.BindableBase.g.cs", source);
            });
    }

    private static Result<HierarchyInfo> ExtractClassInfo(
        GeneratorAttributeSyntaxContext context, System.Threading.CancellationToken token)
    {
        INamedTypeSymbol classSymbol = (INamedTypeSymbol)context.TargetSymbol;

        // Check the class is partial
        bool isPartial = classSymbol.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax(token))
            .OfType<TypeDeclarationSyntax>()
            .Any(static t => t.Modifiers.Any(SyntaxKind.PartialKeyword));

        if (!isPartial)
        {
            return new Result<HierarchyInfo>(
                default!,
                ImmutableArray.Create(
                    DiagnosticInfo.Create(
                        DiagnosticDescriptors.NonPartialClassWithBindableBase,
                        classSymbol,
                        classSymbol.Name)));
        }

        // Check if the class already inherits from BindableBase
        bool inheritsBindableBase = false;
        for (INamedTypeSymbol? baseType = classSymbol.BaseType; baseType is not null; baseType = baseType.BaseType)
        {
            if (baseType.ToDisplayString() == BindableBaseFullName)
            {
                inheritsBindableBase = true;
                break;
            }
        }

        if (inheritsBindableBase)
        {
            // Already inherits BindableBase, no need to generate
            return new Result<HierarchyInfo>(default!, ImmutableArray<DiagnosticInfo>.Empty);
        }

        // Check if the class already implements INotifyPropertyChanged
        bool implementsINPC = classSymbol.AllInterfaces.Any(
            static i => i.ToDisplayString() == "System.ComponentModel.INotifyPropertyChanged");

        // If a base class already implements INPC, skip generation (only generate for the root)
        if (implementsINPC)
        {
            bool baseImplementsINPC = false;
            for (INamedTypeSymbol? baseType = classSymbol.BaseType; baseType is not null; baseType = baseType.BaseType)
            {
                if (baseType.AllInterfaces.Any(
                    static i => i.ToDisplayString() == "System.ComponentModel.INotifyPropertyChanged"))
                {
                    baseImplementsINPC = true;
                    break;
                }
            }

            if (baseImplementsINPC)
            {
                // Base class already has INPC, skip
                return new Result<HierarchyInfo>(default!, ImmutableArray<DiagnosticInfo>.Empty);
            }
        }

        HierarchyInfo hierarchy = HierarchyInfo.From(classSymbol);

        return new Result<HierarchyInfo>(hierarchy, ImmutableArray<DiagnosticInfo>.Empty);
    }

    private static string GenerateBindableBaseSource(HierarchyInfo hierarchy)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        string ns = hierarchy.Namespace;
        if (ns is not "")
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        string indent = ns is not "" ? "    " : "";

        // Open type hierarchy
        var hierarchyArray = hierarchy.Hierarchy.AsImmutableArray();
        foreach (Models.TypeInfo typeInfo in hierarchyArray.Reverse())
        {
            string keyword = typeInfo.IsRecord ? "record" : typeInfo.Kind switch
            {
                TypeKind.Class => "class",
                TypeKind.Struct => "struct",
                _ => "class"
            };

            if (typeInfo == hierarchyArray[0])
            {
                // The target class - add INotifyPropertyChanged interface
                sb.AppendLine($"{indent}partial {keyword} {typeInfo.QualifiedName} : global::System.ComponentModel.INotifyPropertyChanged");
            }
            else
            {
                sb.AppendLine($"{indent}partial {keyword} {typeInfo.QualifiedName}");
            }
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // PropertyChanged event
        sb.AppendLine($"{indent}/// <inheritdoc cref=\"global::System.ComponentModel.INotifyPropertyChanged.PropertyChanged\"/>");
        sb.AppendLine($"{indent}public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();

        // SetProperty<T> method
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Sets the property value and raises <see cref=\"PropertyChanged\"/> if the value has changed.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <typeparam name=\"T\">The type of the property.</typeparam>");
        sb.AppendLine($"{indent}/// <param name=\"storage\">Reference to the backing field.</param>");
        sb.AppendLine($"{indent}/// <param name=\"value\">The new value.</param>");
        sb.AppendLine($"{indent}/// <param name=\"propertyName\">The property name (auto-filled by the compiler).</param>");
        sb.AppendLine($"{indent}/// <returns><see langword=\"true\"/> if the value was changed; otherwise <see langword=\"false\"/>.</returns>");
        sb.AppendLine($"{indent}protected bool SetProperty<T>(ref T storage, T value, [global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(storage, value))");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return false;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    storage = value;");
        sb.AppendLine($"{indent}    RaisePropertyChanged(propertyName);");
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // RaisePropertyChanged method
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Raises the <see cref=\"PropertyChanged\"/> event for the specified property.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"propertyName\">The property name.</param>");
        sb.AppendLine($"{indent}protected void RaisePropertyChanged([global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    OnPropertyChanged(new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // OnPropertyChanged virtual method
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Raises the <see cref=\"PropertyChanged\"/> event.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"args\">The <see cref=\"global::System.ComponentModel.PropertyChangedEventArgs\"/> instance.</param>");
        sb.AppendLine($"{indent}protected virtual void OnPropertyChanged(global::System.ComponentModel.PropertyChangedEventArgs args)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    PropertyChanged?.Invoke(this, args);");
        sb.AppendLine($"{indent}}}");

        // Close type hierarchy
        indent = indent.Substring(0, indent.Length - 4);
        foreach (Models.TypeInfo _ in hierarchyArray)
        {
            sb.AppendLine($"{indent}}}");
            if (indent.Length >= 4) indent = indent.Substring(0, indent.Length - 4);
        }

        if (ns is not "")
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
