using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Prism.SourceGenerators.Diagnostics;
using Prism.SourceGenerators.Helpers;
using Prism.SourceGenerators.Models;

namespace Prism.SourceGenerators;

/// <summary>
/// A source generator that generates <c>INotifyPropertyChanged</c> and <c>SetProperty</c> / <c>RaisePropertyChanged</c> helpers,
/// matching CommunityToolkit.Mvvm <c>ObservableObject</c>, for classes annotated with <c>[BindableBase]</c> that do not inherit <c>Prism.Mvvm.BindableBase</c>.
/// <para>
/// When the type hierarchy does not already implement <c>INotifyPropertyChanging</c>, <see cref="PropertyChangingGenerator"/> emits a companion
/// <c>*.BindableBase.PropertyChanging.g.cs</c> partial. Two-parameter <c>SetProperty</c> calls <c>RaisePropertyChanging</c>; that behavior is gated at runtime by
/// <c>Prism.SourceGenerators.__Internals.FeatureSwitches.EnableINotifyPropertyChangingSupport</c> (default <see langword="true"/>, like the toolkit).
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BindableBaseGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<Result<BindableBaseGenerationInfo>> classInfos =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    BindableBaseMetadataExtractor.BindableBaseAttributeMetadataName,
                    static (node, _) => node is ClassDeclarationSyntax,
                    static (ctx, token) => BindableBaseMetadataExtractor.ExtractGenerationInfo(ctx, token));

        // Report diagnostics
        context.RegisterSourceOutput(
            classInfos.Where(static item => !item.Errors.IsEmpty),
            static (context, result) =>
            {
                foreach (DiagnosticInfo diagnostic in result.Errors.AsImmutableArray())
                {
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());
                }
            });

        // Generate source
        context.RegisterSourceOutput(
            classInfos
                .Where(static item => item.Value is not null && !item.HasBlockingDiagnostics)
                .Select(static (item, _) => item.Value!),
            static (context, info) =>
            {
                string source = GenerateBindableBaseSource(info);
                context.AddSource($"{info.Hierarchy.FilenameHint}.BindableBase.g.cs", source);
            });
    }

    private static string GenerateBindableBaseSource(BindableBaseGenerationInfo model)
    {
        HierarchyInfo hierarchy = model.Hierarchy;

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        string ns = hierarchy.Namespace;
        if (ns is not "")
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        string indent = ns is not "" ? "    " : "";

        // Open type hierarchy
        var hierarchyArray = hierarchy.Hierarchy.AsImmutableArray();
        foreach (Models.TypeInfo typeInfo in hierarchyArray.Reverse())
        {
            string keyword = typeInfo.IsRecord ? "record" : typeInfo.Kind switch
            {
                TypeKind.Class => "class",
                TypeKind.Struct => "struct",
                _ => "class"
            };

            if (typeInfo == hierarchyArray[0])
            {
                sb.AppendLine($"{indent}partial {keyword} {typeInfo.QualifiedName} : global::System.ComponentModel.INotifyPropertyChanged");
            }
            else
            {
                sb.AppendLine($"{indent}partial {keyword} {typeInfo.QualifiedName}");
            }
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // PropertyChanged event
        sb.AppendLine($"{indent}/// <inheritdoc cref=\"global::System.ComponentModel.INotifyPropertyChanged.PropertyChanged\"/>");
        sb.AppendLine($"{indent}public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();

        // SetProperty<T> method (two-parameter): raises PropertyChanging (ObservableObject-style; three-parameter overload does not, for [ObservableProperty] ordering)
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Sets the property value and raises <see cref=\"PropertyChanged\"/> if the value has changed.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <typeparam name=\"T\">The type of the property.</typeparam>");
        sb.AppendLine($"{indent}/// <param name=\"storage\">Reference to the backing field.</param>");
        sb.AppendLine($"{indent}/// <param name=\"value\">The new value.</param>");
        sb.AppendLine($"{indent}/// <param name=\"propertyName\">The property name (auto-filled by the compiler).</param>");
        sb.AppendLine($"{indent}/// <returns><see langword=\"true\"/> if the value was changed; otherwise <see langword=\"false\"/>.</returns>");
        sb.AppendLine($"{indent}protected bool SetProperty<T>(ref T storage, T value, [global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(storage, value))");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return false;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    RaisePropertyChanging(propertyName);");
        sb.AppendLine($"{indent}    storage = value;");
        sb.AppendLine($"{indent}    RaisePropertyChanged(propertyName);");
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Sets the property value, invokes <paramref name=\"onChanged\"/> after assignment, then raises <see cref=\"PropertyChanged\"/>.");
        sb.AppendLine($"{indent}/// Does not raise <see cref=\"global::System.ComponentModel.INotifyPropertyChanging.PropertyChanging\"/> here; callers such as generated <c>[ObservableProperty]</c> setters raise it before changing callbacks.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <typeparam name=\"T\">The type of the property.</typeparam>");
        sb.AppendLine($"{indent}/// <param name=\"storage\">Reference to the backing field.</param>");
        sb.AppendLine($"{indent}/// <param name=\"value\">The new value.</param>");
        sb.AppendLine($"{indent}/// <param name=\"onChanged\">Optional callback invoked after the value is stored and before <see cref=\"PropertyChanged\"/>.</param>");
        sb.AppendLine($"{indent}/// <param name=\"propertyName\">The property name (auto-filled by the compiler).</param>");
        sb.AppendLine($"{indent}/// <returns><see langword=\"true\"/> if the value was changed; otherwise <see langword=\"false\"/>.</returns>");
        sb.AppendLine($"{indent}protected bool SetProperty<T>(ref T storage, T value, global::System.Action? onChanged, [global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(storage, value))");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return false;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    storage = value;");
        sb.AppendLine($"{indent}    onChanged?.Invoke();");
        sb.AppendLine($"{indent}    RaisePropertyChanged(propertyName);");
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // RaisePropertyChanged method
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Raises the <see cref=\"PropertyChanged\"/> event for the specified property.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"propertyName\">The property name.</param>");
        sb.AppendLine($"{indent}protected void RaisePropertyChanged([global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    OnPropertyChanged(new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // OnPropertyChanged virtual method
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Raises the <see cref=\"PropertyChanged\"/> event.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"args\">The <see cref=\"global::System.ComponentModel.PropertyChangedEventArgs\"/> instance.</param>");
        sb.AppendLine($"{indent}protected virtual void OnPropertyChanged(global::System.ComponentModel.PropertyChangedEventArgs args)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    PropertyChanged?.Invoke(this, args);");
        sb.AppendLine($"{indent}}}");

        // Close type hierarchy
        indent = indent.Substring(0, indent.Length - 4);
        foreach (Models.TypeInfo _ in hierarchyArray)
        {
            sb.AppendLine($"{indent}}}");
            if (indent.Length >= 4) indent = indent.Substring(0, indent.Length - 4);
        }

        if (ns is not "")
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
