using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Prism.SourceGenerators.Diagnostics;
using Prism.SourceGenerators.Helpers;
using Prism.SourceGenerators.Models;

namespace Prism.SourceGenerators;

/// <summary>
/// A source generator that generates <c>DelegateCommand</c> / <c>AsyncDelegateCommand</c> properties
/// from methods annotated with <c>[DelegateCommand]</c> or <c>[AsyncDelegateCommand]</c>.
/// <para>
/// For synchronous methods (<c>void</c>), generates <c>DelegateCommand</c> or <c>DelegateCommand&lt;T&gt;</c>.
/// For asynchronous methods (<c>Task</c>), generates <c>AsyncDelegateCommand</c> or <c>AsyncDelegateCommand&lt;T&gt;</c>.
/// If the user's Prism version does not include <c>AsyncDelegateCommand</c> (pre-9.0),
/// a polyfill implementation is generated automatically.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DelegateCommandGenerator : IIncrementalGenerator
{
    private const string DelegateCommandAttributeName = "Prism.SourceGenerators.DelegateCommandAttribute";
    private const string AsyncDelegateCommandAttributeName = "Prism.SourceGenerators.AsyncDelegateCommandAttribute";
    private const string ObservesPropertyAttributeName = "Prism.SourceGenerators.ObservesPropertyAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the DelegateCommand attribute
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("DelegateCommandAttribute.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace Prism.SourceGenerators;

                /// <summary>
                /// An attribute that can be applied to a method to generate a <c>DelegateCommand</c>
                /// or <c>AsyncDelegateCommand</c> property.
                /// <para>
                /// For synchronous methods (<c>void</c>), generates <c>DelegateCommand</c> or <c>DelegateCommand&lt;T&gt;</c>.
                /// For asynchronous methods (<c>Task</c>), generates <c>AsyncDelegateCommand</c> or <c>AsyncDelegateCommand&lt;T&gt;</c>.
                /// </para>
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                [global::System.Diagnostics.Conditional("PRISM_SOURCEGENERATORS_ATTRIBUTES")]
                internal sealed class DelegateCommandAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// Gets or sets the name of the generated command property.
                    /// If not specified, the name is derived from the method name
                    /// (e.g., <c>Submit</c> becomes <c>SubmitCommand</c>).
                    /// </summary>
                    public string? CommandName { get; set; }

                    /// <summary>
                    /// Gets or sets the name of the <c>CanExecute</c> method or property.
                    /// </summary>
                    public string? CanExecute { get; set; }
                }
                """);

            ctx.AddSource("AsyncDelegateCommandAttribute.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace Prism.SourceGenerators;

                /// <summary>
                /// An attribute that can be applied to an async method to generate an <c>AsyncDelegateCommand</c> property.
                /// Supports Prism 9.0+ fluent configuration methods.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
                [global::System.Diagnostics.Conditional("PRISM_SOURCEGENERATORS_ATTRIBUTES")]
                internal sealed class AsyncDelegateCommandAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// Gets or sets the name of the generated command property.
                    /// If not specified, the name is derived from the method name
                    /// (e.g., <c>Submit</c> becomes <c>SubmitCommand</c>).
                    /// </summary>
                    public string? CommandName { get; set; }

                    /// <summary>
                    /// Gets or sets the name of the <c>CanExecute</c> method or property.
                    /// </summary>
                    public string? CanExecute { get; set; }

                    /// <summary>
                    /// Gets or sets the timeout in microseconds for <c>AsyncDelegateCommand.CancelAfter(TimeSpan)</c>.
                    /// </summary>
                    public double CancelAfterMicroseconds { get; set; }

                    /// <summary>
                    /// Gets or sets the name of the error handler for <c>AsyncDelegateCommand.Catch</c>.
                    /// Can be a method (with Exception parameter), field, or property (Action&lt;Exception&gt;).
                    /// </summary>
                    public string? Catch { get; set; }

                    /// <summary>
                    /// Gets or sets the name of the CancellationToken factory for
                    /// <c>AsyncDelegateCommand.CancellationTokenSourceFactory</c>.
                    /// </summary>
                    public string? CancellationTokenSourceFactory { get; set; }

                    /// <summary>
                    /// Gets or sets whether to enable parallel execution via
                    /// <c>AsyncDelegateCommand.EnableParallelExecution()</c>.
                    /// </summary>
                    public bool EnableParallelExecution { get; set; }
                }
                """);

            ctx.AddSource("ObservesPropertyAttribute.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace Prism.SourceGenerators;

                /// <summary>
                /// An attribute that can be applied to a method (alongside [DelegateCommand] or [AsyncDelegateCommand])
                /// to observe property changes and automatically re-evaluate CanExecute.
                /// Corresponds to <c>DelegateCommand.ObservesProperty</c> / <c>AsyncDelegateCommand.ObservesProperty</c>.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
                [global::System.Diagnostics.Conditional("PRISM_SOURCEGENERATORS_ATTRIBUTES")]
                internal sealed class ObservesPropertyAttribute : global::System.Attribute
                {
                    public ObservesPropertyAttribute(string propertyName, params string[] otherPropertyNames)
                    {
                        PropertyName = propertyName;
                        OtherPropertyNames = otherPropertyNames;
                    }

                    public string PropertyName { get; }
                    public string[] OtherPropertyNames { get; }
                }
                """);
        });

        // --- [DelegateCommand] pipeline ---
        IncrementalValuesProvider<Result<CommandGenerationInfo>> delegateCommandInfos =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    DelegateCommandAttributeName,
                    static (node, _) => node is MethodDeclarationSyntax
                    {
                        Parent: ClassDeclarationSyntax or RecordDeclarationSyntax
                    },
                    static (context, token) => ExtractDelegateCommandInfo(context, token));

        RegisterDiagnosticsAndCommands(context, delegateCommandInfos);

        // --- [AsyncDelegateCommand] pipeline (AllowMultiple=true, one command per attribute) ---
        IncrementalValuesProvider<Result<CommandGenerationInfo>> asyncCommandInfos =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AsyncDelegateCommandAttributeName,
                    static (node, _) => node is MethodDeclarationSyntax
                    {
                        Parent: ClassDeclarationSyntax or RecordDeclarationSyntax
                    },
                    static (context, token) => ExtractAsyncDelegateCommandInfos(context, token))
                .SelectMany(static (results, _) => results);

        RegisterDiagnosticsAndCommands(context, asyncCommandInfos);

        // --- Polyfill generation (combined from both pipelines, emitted once) ---
        IncrementalValueProvider<bool> needsPolyfillFromDelegate = delegateCommandInfos
            .Where(static item => item.Value is not null && item.Errors.IsEmpty)
            .Select(static (item, _) => item.Value!)
            .Where(static item => item.IsAsync && !item.HasAsyncDelegateCommand)
            .Collect()
            .Select(static (items, _) => items.Length > 0);

        IncrementalValueProvider<bool> needsPolyfillFromAsync = asyncCommandInfos
            .Where(static item => item.Value is not null && item.Errors.IsEmpty)
            .Select(static (item, _) => item.Value!)
            .Where(static item => !item.HasAsyncDelegateCommand)
            .Collect()
            .Select(static (items, _) => items.Length > 0);

        IncrementalValueProvider<bool> needsPolyfill = needsPolyfillFromDelegate
            .Combine(needsPolyfillFromAsync)
            .Select(static (pair, _) => pair.Left || pair.Right);

        context.RegisterSourceOutput(needsPolyfill, static (context, needs) =>
        {
            if (needs)
            {
                context.AddSource("AsyncDelegateCommand.Polyfill.g.cs", GenerateAsyncDelegateCommandPolyfill());
            }
        });
    }

    private static void RegisterDiagnosticsAndCommands(
        IncrementalGeneratorInitializationContext context,
        IncrementalValuesProvider<Result<CommandGenerationInfo>> commandInfos)
    {
        // Report diagnostics
        context.RegisterSourceOutput(
            commandInfos.Where(static item => !item.Errors.IsEmpty),
            static (context, result) =>
            {
                foreach (DiagnosticInfo diagnostic in result.Errors.AsImmutableArray())
                {
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());
                }
            });

        // Generate command properties
        context.RegisterSourceOutput(
            commandInfos
                .Where(static item => item.Value is not null && item.Errors.IsEmpty)
                .Select(static (item, _) => item.Value!),
            static (context, info) =>
            {
                string source = GenerateCommandSource(info);
                context.AddSource(
                    $"{info.Hierarchy.FilenameHint}.{info.CommandName}.g.cs",
                    source);
            });
    }

    private static Result<CommandGenerationInfo> ExtractDelegateCommandInfo(
        GeneratorAttributeSyntaxContext context, System.Threading.CancellationToken token)
    {
        IMethodSymbol methodSymbol = (IMethodSymbol)context.TargetSymbol;
        INamedTypeSymbol containingType = methodSymbol.ContainingType;

        if (!IsPartialType(containingType, token))
        {
            return CreateNonPartialDiagnostic(containingType);
        }

        bool isAsync = IsAsyncMethod(methodSymbol, context.SemanticModel.Compilation);

        string? parameterType = ExtractParameterType(methodSymbol, isAsync);
        string methodName = methodSymbol.Name;
        string? commandName = null;
        string? canExecute = null;

        foreach (AttributeData attr in methodSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == DelegateCommandAttributeName)
            {
                foreach (var namedArg in attr.NamedArguments)
                {
                    if (namedArg.Key == "CommandName" && namedArg.Value.Value is string cn)
                        commandName = cn;
                    else if (namedArg.Key == "CanExecute" && namedArg.Value.Value is string ce)
                        canExecute = ce;
                }
            }
        }

        commandName ??= GetCommandName(methodName);

        ImmutableArray<string> observesProperties = CollectObservesProperties(methodSymbol);

        bool hasAsyncDelegateCommand = context.SemanticModel.Compilation
            .GetTypeByMetadataName("Prism.Commands.AsyncDelegateCommand") is not null;

        HierarchyInfo hierarchy = HierarchyInfo.From(containingType);

        bool useFieldKeyword = SupportsFieldKeyword(context);

        return new Result<CommandGenerationInfo>(
            new CommandGenerationInfo(
                hierarchy,
                methodName,
                commandName,
                parameterType,
                isAsync,
                canExecute,
                hasAsyncDelegateCommand,
                CancelAfterMicroseconds: null,
                Catch: null,
                CancellationTokenSourceFactory: null,
                EnableParallelExecution: false,
                ObservesProperties: observesProperties,
                UseFieldKeyword: useFieldKeyword),
            ImmutableArray<DiagnosticInfo>.Empty);
    }

    private static ImmutableArray<Result<CommandGenerationInfo>> ExtractAsyncDelegateCommandInfos(
        GeneratorAttributeSyntaxContext context, System.Threading.CancellationToken token)
    {
        IMethodSymbol methodSymbol = (IMethodSymbol)context.TargetSymbol;
        INamedTypeSymbol containingType = methodSymbol.ContainingType;

        if (!IsPartialType(containingType, token))
        {
            return ImmutableArray.Create(CreateNonPartialDiagnostic(containingType));
        }

        string? parameterType = ExtractParameterType(methodSymbol, isAsync: true);
        string methodName = methodSymbol.Name;
        ImmutableArray<string> observesProperties = CollectObservesProperties(methodSymbol);
        bool hasAsyncDelegateCommand = context.SemanticModel.Compilation
            .GetTypeByMetadataName("Prism.Commands.AsyncDelegateCommand") is not null;
        HierarchyInfo hierarchy = HierarchyInfo.From(containingType);
        bool useFieldKeyword = SupportsFieldKeyword(context);

        ImmutableArray<Result<CommandGenerationInfo>>.Builder builder =
            ImmutableArray.CreateBuilder<Result<CommandGenerationInfo>>();

        foreach (AttributeData attr in methodSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != AsyncDelegateCommandAttributeName)
                continue;

            string? commandName = null;
            string? canExecute = null;
            double? cancelAfterMicroseconds = null;
            string? catchHandler = null;
            string? cancellationTokenSourceFactory = null;
            bool enableParallelExecution = false;

            foreach (var namedArg in attr.NamedArguments)
            {
                switch (namedArg.Key)
                {
                    case "CommandName" when namedArg.Value.Value is string cn:
                        commandName = cn;
                        break;
                    case "CanExecute" when namedArg.Value.Value is string ce:
                        canExecute = ce;
                        break;
                    case "CancelAfterMicroseconds" when namedArg.Value.Value is double ms:
                        cancelAfterMicroseconds = ms;
                        break;
                    case "Catch" when namedArg.Value.Value is string ch:
                        catchHandler = ch;
                        break;
                    case "CancellationTokenSourceFactory" when namedArg.Value.Value is string ctsf:
                        cancellationTokenSourceFactory = ctsf;
                        break;
                    case "EnableParallelExecution" when namedArg.Value.Value is bool epe:
                        enableParallelExecution = epe;
                        break;
                }
            }

            commandName ??= GetCommandName(methodName);

            builder.Add(new Result<CommandGenerationInfo>(
                new CommandGenerationInfo(
                    hierarchy,
                    methodName,
                    commandName,
                    parameterType,
                    IsAsync: true,
                    canExecute,
                    hasAsyncDelegateCommand,
                    cancelAfterMicroseconds,
                    catchHandler,
                    cancellationTokenSourceFactory,
                    enableParallelExecution,
                    observesProperties,
                    useFieldKeyword),
                ImmutableArray<DiagnosticInfo>.Empty));
        }

        return builder.ToImmutable();
    }

    private static ImmutableArray<string> CollectObservesProperties(IMethodSymbol methodSymbol)
    {
        ImmutableArray<string>.Builder? builder = null;

        foreach (AttributeData attr in methodSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != ObservesPropertyAttributeName)
                continue;

            // First constructor arg is propertyName
            if (attr.ConstructorArguments.Length >= 1 && attr.ConstructorArguments[0].Value is string propName)
            {
                builder ??= ImmutableArray.CreateBuilder<string>();
                builder.Add(propName);

                // params string[] otherPropertyNames
                if (attr.ConstructorArguments.Length >= 2 && !attr.ConstructorArguments[1].IsNull)
                {
                    foreach (var item in attr.ConstructorArguments[1].Values)
                    {
                        if (item.Value is string otherProp)
                            builder.Add(otherProp);
                    }
                }
            }
        }

        return builder?.ToImmutable() ?? ImmutableArray<string>.Empty;
    }

    private static bool IsPartialType(INamedTypeSymbol containingType, System.Threading.CancellationToken token)
    {
        return containingType.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax(token))
            .OfType<TypeDeclarationSyntax>()
            .Any(static t => t.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static Result<CommandGenerationInfo> CreateNonPartialDiagnostic(INamedTypeSymbol containingType)
    {
        return new Result<CommandGenerationInfo>(
            default!,
            ImmutableArray.Create(
                DiagnosticInfo.Create(
                    DiagnosticDescriptors.NonPartialClassWithDelegateCommand,
                    containingType,
                    containingType.Name)));
    }

    private static string? ExtractParameterType(IMethodSymbol methodSymbol, bool isAsync)
    {
        if (isAsync && methodSymbol.Parameters.Length == 1)
        {
            IParameterSymbol param = methodSymbol.Parameters[0];
            if (!IsCancellationToken(param.Type))
            {
                return param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }
        else if (isAsync && methodSymbol.Parameters.Length == 2
            && IsCancellationToken(methodSymbol.Parameters[1].Type))
        {
            return methodSymbol.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
        else if (!isAsync && methodSymbol.Parameters.Length == 1)
        {
            return methodSymbol.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return null;
    }

    private static bool IsAsyncMethod(IMethodSymbol method, Compilation compilation)
    {
        INamedTypeSymbol? taskType = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task");
        INamedTypeSymbol? taskOfTType = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task`1");

        if (taskType is null)
            return false;

        return SymbolEqualityComparer.Default.Equals(method.ReturnType, taskType)
            || (method.ReturnType is INamedTypeSymbol namedReturn
                && namedReturn.IsGenericType
                && SymbolEqualityComparer.Default.Equals(namedReturn.ConstructedFrom, taskOfTType));
    }

    private static bool IsCancellationToken(ITypeSymbol type)
    {
        return type.ToDisplayString() == "System.Threading.CancellationToken";
    }

    private static bool SupportsFieldKeyword(GeneratorAttributeSyntaxContext context)
    {
        var parseOptions = (CSharpParseOptions)context.SemanticModel.SyntaxTree.Options;
        // field keyword is stable in C# 14 (1400), preview in C# 13
        return (int)parseOptions.LanguageVersion >= 1400;
    }

    private static string GetCommandName(string methodName)
    {
        if (methodName.EndsWith("Async"))
            methodName = methodName.Substring(0, methodName.Length - 5);
        return methodName + "Command";
    }

    private static string GenerateCommandSource(CommandGenerationInfo info)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        string ns = info.Hierarchy.Namespace;
        if (ns is not "")
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        // Open type hierarchy
        foreach (Models.TypeInfo typeInfo in info.Hierarchy.Hierarchy.AsImmutableArray().Reverse())
        {
            string keyword = typeInfo.IsRecord ? "record" : typeInfo.Kind switch
            {
                TypeKind.Class => "class",
                TypeKind.Struct => "struct",
                _ => "class"
            };
            sb.AppendLine($"    partial {keyword} {typeInfo.QualifiedName}");
            sb.AppendLine("    {");
        }

        // Determine command type
        string commandType;
        string initialization;

        if (info.IsAsync)
        {
            if (info.ParameterType is not null)
            {
                commandType = $"global::Prism.Commands.AsyncDelegateCommand<{info.ParameterType}>";
                initialization = info.CanExecute is not null
                    ? $"new {commandType}({info.MethodName}, {info.CanExecute})"
                    : $"new {commandType}({info.MethodName})";
            }
            else
            {
                commandType = "global::Prism.Commands.AsyncDelegateCommand";
                initialization = info.CanExecute is not null
                    ? $"new {commandType}({info.MethodName}, {info.CanExecute})"
                    : $"new {commandType}({info.MethodName})";
            }
        }
        else
        {
            if (info.ParameterType is not null)
            {
                commandType = $"global::Prism.Commands.DelegateCommand<{info.ParameterType}>";
                initialization = info.CanExecute is not null
                    ? $"new {commandType}({info.MethodName}, {info.CanExecute})"
                    : $"new {commandType}({info.MethodName})";
            }
            else
            {
                commandType = "global::Prism.Commands.DelegateCommand";
                initialization = info.CanExecute is not null
                    ? $"new {commandType}({info.MethodName}, {info.CanExecute})"
                    : $"new {commandType}({info.MethodName})";
            }
        }

        // Append fluent builder calls for async commands
        bool hasFluentCalls = info.IsAsync && (
            info.EnableParallelExecution ||
            info.CancelAfterMicroseconds is not null ||
            info.CancellationTokenSourceFactory is not null ||
            info.Catch is not null);

        bool hasObservesProperty = info.ObservesProperties.AsImmutableArray().Length > 0;

        if (hasFluentCalls || hasObservesProperty)
        {
            StringBuilder fluentSb = new();
            fluentSb.Append(initialization);

            if (info.EnableParallelExecution)
                fluentSb.Append("\n                .EnableParallelExecution()");

            if (info.CancelAfterMicroseconds is { } microseconds)
            {
                string timespan = $"global::System.TimeSpan.FromMicroseconds({microseconds})";
                fluentSb.Append($"\n                .CancelAfter({timespan})");
            }

            if (info.CancellationTokenSourceFactory is { } ctsFactory)
                fluentSb.Append($"\n                .CancellationTokenSourceFactory({ctsFactory})");

            if (info.Catch is { } catchHandler)
                fluentSb.Append($"\n                .Catch({catchHandler})");

            foreach (string prop in info.ObservesProperties.AsImmutableArray())
            {
                fluentSb.Append($"\n                .ObservesProperty(() => {prop})");
            }

            initialization = fluentSb.ToString();
        }

        if (info.UseFieldKeyword)
        {
            sb.AppendLine($"        public {commandType} {info.CommandName} => field ??= {initialization};");
        }
        else
        {
            string fieldName = $"_{char.ToLowerInvariant(info.CommandName[0])}{info.CommandName.Substring(1)}";
            sb.AppendLine($"        private {commandType}? {fieldName};");
            sb.AppendLine();
            sb.AppendLine($"        public {commandType} {info.CommandName} => {fieldName} ??= {initialization};");
        }

        // Close type hierarchy
        foreach (Models.TypeInfo _ in info.Hierarchy.Hierarchy.AsImmutableArray())
        {
            sb.AppendLine("    }");
        }

        if (ns is not "")
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateAsyncDelegateCommandPolyfill()
    {
        return """
            // <auto-generated/>
            // Polyfill for AsyncDelegateCommand (Prism < 9.0)
            // Prism 8.x DelegateCommandBase does not inherit BindableBase,
            // so we implement IsExecuting manually without SetProperty.
            #pragma warning disable
            #nullable enable

            using System;
            using System.Linq.Expressions;
            using System.Runtime.ExceptionServices;
            using System.Threading;
            using System.Threading.Tasks;
            using System.Windows.Input;

            namespace Prism.Commands
            {
                /// <summary>
                /// Polyfill for <c>AsyncDelegateCommand</c> for Prism versions prior to 9.0.
                /// </summary>
                public class AsyncDelegateCommand : DelegateCommandBase
                {
                    private bool _isExecuting;
                    private bool _enableParallelExecution;
                    private readonly Func<Task> _executeMethod;
                    private readonly Func<bool>? _canExecuteMethod;
                    private Action<Exception>? _catchHandler;
                    private Func<CancellationToken>? _getCancellationToken;

                    public AsyncDelegateCommand(Func<Task> executeMethod)
                        : this(executeMethod, null)
                    {
                    }

                    public AsyncDelegateCommand(Func<Task> executeMethod, Func<bool>? canExecuteMethod)
                    {
                        _executeMethod = executeMethod ?? throw new ArgumentNullException(nameof(executeMethod));
                        _canExecuteMethod = canExecuteMethod;
                    }

                    public bool IsExecuting
                    {
                        get => _isExecuting;
                        private set
                        {
                            _isExecuting = value;
                            RaiseCanExecuteChanged();
                        }
                    }

                    public async Task Execute()
                    {
                        if (!_enableParallelExecution && IsExecuting) return;
                        try
                        {
                            IsExecuting = true;
                            await _executeMethod().ConfigureAwait(false);
                        }
                        catch (Exception ex)
                        {
                            if (_catchHandler != null)
                                _catchHandler(ex);
                            else
                                throw;
                        }
                        finally
                        {
                            IsExecuting = false;
                        }
                    }

                    protected override async void Execute(object parameter)
                    {
                        await Execute().ConfigureAwait(false);
                    }

                    protected override bool CanExecute(object parameter)
                    {
                        if (!_enableParallelExecution && IsExecuting) return false;
                        return _canExecuteMethod?.Invoke() ?? true;
                    }

                    public AsyncDelegateCommand EnableParallelExecution()
                    {
                        _enableParallelExecution = true;
                        return this;
                    }

                    public AsyncDelegateCommand CancelAfter(TimeSpan timeout)
                    {
                        // Simplified polyfill: CancelAfter is a no-op for Prism < 9.0
                        return this;
                    }

                    public AsyncDelegateCommand CancellationTokenSourceFactory(Func<CancellationToken> factory)
                    {
                        _getCancellationToken = factory;
                        return this;
                    }

                    public AsyncDelegateCommand Catch(Action<Exception> handler)
                    {
                        _catchHandler = handler;
                        return this;
                    }

                    public AsyncDelegateCommand Catch<TException>(Action<TException> handler) where TException : Exception
                    {
                        _catchHandler = ex =>
                        {
                            if (ex is TException typed)
                                handler(typed);
                            else
                                ExceptionDispatchInfo.Capture(ex).Throw();
                        };
                        return this;
                    }

                    public AsyncDelegateCommand ObservesProperty<T>(Expression<Func<T>> propertyExpression)
                    {
                        ObservesPropertyInternal(propertyExpression);
                        return this;
                    }
                }

                /// <summary>
                /// Polyfill for <c>AsyncDelegateCommand&lt;T&gt;</c> for Prism versions prior to 9.0.
                /// </summary>
                public class AsyncDelegateCommand<T> : DelegateCommandBase
                {
                    private bool _isExecuting;
                    private bool _enableParallelExecution;
                    private readonly Func<T, Task> _executeMethod;
                    private readonly Func<T, bool>? _canExecuteMethod;
                    private Action<Exception>? _catchHandler;
                    private Func<CancellationToken>? _getCancellationToken;

                    public AsyncDelegateCommand(Func<T, Task> executeMethod)
                        : this(executeMethod, null)
                    {
                    }

                    public AsyncDelegateCommand(Func<T, Task> executeMethod, Func<T, bool>? canExecuteMethod)
                    {
                        _executeMethod = executeMethod ?? throw new ArgumentNullException(nameof(executeMethod));
                        _canExecuteMethod = canExecuteMethod;
                    }

                    public bool IsExecuting
                    {
                        get => _isExecuting;
                        private set
                        {
                            _isExecuting = value;
                            RaiseCanExecuteChanged();
                        }
                    }

                    public async Task Execute(T parameter)
                    {
                        if (!_enableParallelExecution && IsExecuting) return;
                        try
                        {
                            IsExecuting = true;
                            await _executeMethod(parameter).ConfigureAwait(false);
                        }
                        catch (Exception ex)
                        {
                            if (_catchHandler != null)
                                _catchHandler(ex);
                            else
                                throw;
                        }
                        finally
                        {
                            IsExecuting = false;
                        }
                    }

                    protected override async void Execute(object parameter)
                    {
                        await Execute((T)parameter!).ConfigureAwait(false);
                    }

                    protected override bool CanExecute(object parameter)
                    {
                        if (!_enableParallelExecution && IsExecuting) return false;
                        return _canExecuteMethod?.Invoke((T)parameter!) ?? true;
                    }

                    public AsyncDelegateCommand<T> EnableParallelExecution()
                    {
                        _enableParallelExecution = true;
                        return this;
                    }

                    public AsyncDelegateCommand<T> CancelAfter(TimeSpan timeout)
                    {
                        return this;
                    }

                    public AsyncDelegateCommand<T> CancellationTokenSourceFactory(Func<CancellationToken> factory)
                    {
                        _getCancellationToken = factory;
                        return this;
                    }

                    public AsyncDelegateCommand<T> Catch(Action<Exception> handler)
                    {
                        _catchHandler = handler;
                        return this;
                    }

                    public AsyncDelegateCommand<T> Catch<TException>(Action<TException> handler) where TException : Exception
                    {
                        _catchHandler = ex =>
                        {
                            if (ex is TException typed)
                                handler(typed);
                            else
                                ExceptionDispatchInfo.Capture(ex).Throw();
                        };
                        return this;
                    }

                    public AsyncDelegateCommand<T> ObservesProperty<TProperty>(Expression<Func<TProperty>> propertyExpression)
                    {
                        ObservesPropertyInternal(propertyExpression);
                        return this;
                    }
                }
            }
            """;
    }
}
