using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Prism.SourceGenerators.Diagnostics;
using Prism.SourceGenerators.Helpers;
using Prism.SourceGenerators.Models;

namespace Prism.SourceGenerators;

/// <summary>
/// A source generator that generates <c>DelegateCommand</c> / <c>AsyncDelegateCommand</c> properties
/// from methods annotated with <c>[DelegateCommand]</c>.
/// <para>
/// For synchronous methods (<c>void</c>), generates <c>DelegateCommand</c> or <c>DelegateCommand&lt;T&gt;</c>.
/// For asynchronous methods (<c>Task</c>), generates <c>AsyncDelegateCommand</c> or <c>AsyncDelegateCommand&lt;T&gt;</c>.
/// If the user's Prism version does not include <c>AsyncDelegateCommand</c> (pre-9.0),
/// a polyfill implementation is generated automatically.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DelegateCommandGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the DelegateCommand attribute
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("DelegateCommandAttribute.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace Prism.SourceGenerators;

                /// <summary>
                /// An attribute that can be applied to a method to generate a <c>DelegateCommand</c>
                /// or <c>AsyncDelegateCommand</c> property.
                /// <para>
                /// For synchronous methods (<c>void</c>), generates <c>DelegateCommand</c> or <c>DelegateCommand&lt;T&gt;</c>.
                /// For asynchronous methods (<c>Task</c>), generates <c>AsyncDelegateCommand</c> or <c>AsyncDelegateCommand&lt;T&gt;</c>.
                /// </para>
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                [global::System.Diagnostics.Conditional("PRISM_SOURCEGENERATORS_ATTRIBUTES")]
                internal sealed class DelegateCommandAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// Gets or sets the name of the generated command property.
                    /// If not specified, the name is derived from the method name
                    /// (e.g., <c>Submit</c> becomes <c>SubmitCommand</c>).
                    /// </summary>
                    public string? CommandName { get; set; }

                    /// <summary>
                    /// Gets or sets the name of the <c>CanExecute</c> method or property.
                    /// </summary>
                    public string? CanExecute { get; set; }
                }
                """);
        });

        // Collect method info
        IncrementalValuesProvider<Result<CommandGenerationInfo>> commandInfos =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Prism.SourceGenerators.DelegateCommandAttribute",
                    static (node, _) => node is MethodDeclarationSyntax
                    {
                        Parent: ClassDeclarationSyntax or RecordDeclarationSyntax
                    },
                    static (context, token) =>
                    {
                        IMethodSymbol methodSymbol = (IMethodSymbol)context.TargetSymbol;
                        INamedTypeSymbol containingType = methodSymbol.ContainingType;

                        // Check partial
                        bool isPartial = containingType.DeclaringSyntaxReferences
                            .Select(r => r.GetSyntax(token))
                            .OfType<TypeDeclarationSyntax>()
                            .Any(static t => t.Modifiers.Any(SyntaxKind.PartialKeyword));

                        if (!isPartial)
                        {
                            return new Result<CommandGenerationInfo>(
                                default!,
                                ImmutableArray.Create(
                                    DiagnosticInfo.Create(
                                        DiagnosticDescriptors.NonPartialClassWithDelegateCommand,
                                        containingType,
                                        containingType.Name)));
                        }

                        // Determine if async
                        bool isAsync = IsAsyncMethod(methodSymbol, context.SemanticModel.Compilation);

                        // Determine parameter type
                        string? parameterType = null;
                        if (isAsync && methodSymbol.Parameters.Length == 1)
                        {
                            // For async: check if single param is CancellationToken (skip it)
                            IParameterSymbol param = methodSymbol.Parameters[0];
                            if (!IsCancellationToken(param.Type))
                            {
                                parameterType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            }
                        }
                        else if (isAsync && methodSymbol.Parameters.Length == 2)
                        {
                            // (T param, CancellationToken ct)
                            parameterType = methodSymbol.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        }
                        else if (!isAsync && methodSymbol.Parameters.Length == 1)
                        {
                            parameterType = methodSymbol.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        }

                        // Get command name from attribute or derive from method name
                        string methodName = methodSymbol.Name;
                        string? commandName = null;
                        string? canExecute = null;

                        foreach (AttributeData attr in methodSymbol.GetAttributes())
                        {
                            if (attr.AttributeClass?.ToDisplayString() == "Prism.SourceGenerators.DelegateCommandAttribute")
                            {
                                foreach (var namedArg in attr.NamedArguments)
                                {
                                    if (namedArg.Key == "CommandName" && namedArg.Value.Value is string cn)
                                        commandName = cn;
                                    else if (namedArg.Key == "CanExecute" && namedArg.Value.Value is string ce)
                                        canExecute = ce;
                                }
                            }
                        }

                        commandName ??= GetCommandName(methodName);

                        // Check if AsyncDelegateCommand is available in the compilation
                        bool hasAsyncDelegateCommand = context.SemanticModel.Compilation
                            .GetTypeByMetadataName("Prism.Commands.AsyncDelegateCommand") is not null;

                        HierarchyInfo hierarchy = HierarchyInfo.From(containingType);

                        return new Result<CommandGenerationInfo>(
                            new CommandGenerationInfo(
                                hierarchy,
                                methodName,
                                commandName,
                                parameterType,
                                isAsync,
                                canExecute,
                                hasAsyncDelegateCommand),
                            ImmutableArray<DiagnosticInfo>.Empty);
                    });

        // Report diagnostics
        context.RegisterSourceOutput(
            commandInfos.Where(static item => !item.Errors.IsEmpty),
            static (context, result) =>
            {
                foreach (DiagnosticInfo diagnostic in result.Errors.AsImmutableArray())
                {
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());
                }
            });

        // Generate polyfill if needed (once per compilation)
        IncrementalValueProvider<bool> needsPolyfill = commandInfos
            .Where(static item => item.Value is not null && item.Errors.IsEmpty)
            .Select(static (item, _) => item.Value!)
            .Where(static item => item.IsAsync && !item.HasAsyncDelegateCommand)
            .Collect()
            .Select(static (items, _) => items.Length > 0);

        context.RegisterSourceOutput(needsPolyfill, static (context, needs) =>
        {
            if (needs)
            {
                context.AddSource("AsyncDelegateCommand.Polyfill.g.cs", GenerateAsyncDelegateCommandPolyfill());
            }
        });

        // Generate command properties
        context.RegisterSourceOutput(
            commandInfos
                .Where(static item => item.Value is not null && item.Errors.IsEmpty)
                .Select(static (item, _) => item.Value!),
            static (context, info) =>
            {
                string source = GenerateCommandSource(info);
                context.AddSource(
                    $"{info.Hierarchy.FilenameHint}.{info.CommandName}.g.cs",
                    source);
            });
    }

    private static bool IsAsyncMethod(IMethodSymbol method, Compilation compilation)
    {
        INamedTypeSymbol? taskType = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task");
        INamedTypeSymbol? taskOfTType = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task`1");

        if (taskType is null)
            return false;

        return SymbolEqualityComparer.Default.Equals(method.ReturnType, taskType)
            || (method.ReturnType is INamedTypeSymbol namedReturn
                && namedReturn.IsGenericType
                && SymbolEqualityComparer.Default.Equals(namedReturn.ConstructedFrom, taskOfTType));
    }

    private static bool IsCancellationToken(ITypeSymbol type)
    {
        return type.ToDisplayString() == "System.Threading.CancellationToken";
    }

    private static string GetCommandName(string methodName)
    {
        // Remove "Async" suffix if present, then add "Command"
        if (methodName.EndsWith("Async"))
            methodName = methodName.Substring(0, methodName.Length - 5);
        return methodName + "Command";
    }

    private static string GenerateCommandSource(CommandGenerationInfo info)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        string ns = info.Hierarchy.Namespace;
        if (ns is not "")
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        // Open type hierarchy
        foreach (Models.TypeInfo typeInfo in info.Hierarchy.Hierarchy.AsImmutableArray().Reverse())
        {
            string keyword = typeInfo.IsRecord ? "record" : typeInfo.Kind switch
            {
                TypeKind.Class => "class",
                TypeKind.Struct => "struct",
                _ => "class"
            };
            sb.AppendLine($"    partial {keyword} {typeInfo.QualifiedName}");
            sb.AppendLine("    {");
        }

        // Determine command type
        string commandType;
        string fieldType;
        string initialization;

        if (info.IsAsync)
        {
            if (info.ParameterType is not null)
            {
                commandType = $"global::Prism.Commands.AsyncDelegateCommand<{info.ParameterType}>";
                if (info.CanExecute is not null)
                    initialization = $"new {commandType}({info.MethodName}, {info.CanExecute})";
                else
                    initialization = $"new {commandType}({info.MethodName})";
            }
            else
            {
                commandType = "global::Prism.Commands.AsyncDelegateCommand";
                if (info.CanExecute is not null)
                    initialization = $"new {commandType}({info.MethodName}, {info.CanExecute})";
                else
                    initialization = $"new {commandType}({info.MethodName})";
            }
        }
        else
        {
            if (info.ParameterType is not null)
            {
                commandType = $"global::Prism.Commands.DelegateCommand<{info.ParameterType}>";
                if (info.CanExecute is not null)
                    initialization = $"new {commandType}({info.MethodName}, {info.CanExecute})";
                else
                    initialization = $"new {commandType}({info.MethodName})";
            }
            else
            {
                commandType = "global::Prism.Commands.DelegateCommand";
                if (info.CanExecute is not null)
                    initialization = $"new {commandType}({info.MethodName}, {info.CanExecute})";
                else
                    initialization = $"new {commandType}({info.MethodName})";
            }
        }

        fieldType = $"{commandType}?";

        sb.AppendLine($"        private {fieldType} _{char.ToLowerInvariant(info.CommandName[0])}{info.CommandName.Substring(1)};");
        sb.AppendLine();
        sb.AppendLine($"        public {commandType} {info.CommandName} => _{char.ToLowerInvariant(info.CommandName[0])}{info.CommandName.Substring(1)} ??= {initialization};");

        // Close type hierarchy
        foreach (Models.TypeInfo _ in info.Hierarchy.Hierarchy.AsImmutableArray())
        {
            sb.AppendLine("    }");
        }

        if (ns is not "")
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateAsyncDelegateCommandPolyfill()
    {
        return """
            // <auto-generated/>
            // Polyfill for AsyncDelegateCommand (Prism < 9.0)
            // Prism 8.x DelegateCommandBase does not inherit BindableBase,
            // so we implement IsExecuting manually without SetProperty.
            #pragma warning disable
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using System.Windows.Input;

            namespace Prism.Commands
            {
                /// <summary>
                /// Polyfill for <c>AsyncDelegateCommand</c> for Prism versions prior to 9.0.
                /// </summary>
                public class AsyncDelegateCommand : DelegateCommandBase
                {
                    private bool _isExecuting;
                    private readonly Func<Task> _executeMethod;
                    private readonly Func<bool>? _canExecuteMethod;

                    public AsyncDelegateCommand(Func<Task> executeMethod)
                        : this(executeMethod, null)
                    {
                    }

                    public AsyncDelegateCommand(Func<Task> executeMethod, Func<bool>? canExecuteMethod)
                    {
                        _executeMethod = executeMethod ?? throw new ArgumentNullException(nameof(executeMethod));
                        _canExecuteMethod = canExecuteMethod;
                    }

                    public bool IsExecuting
                    {
                        get => _isExecuting;
                        private set
                        {
                            _isExecuting = value;
                            RaiseCanExecuteChanged();
                        }
                    }

                    public async Task Execute()
                    {
                        if (IsExecuting) return;
                        try
                        {
                            IsExecuting = true;
                            await _executeMethod().ConfigureAwait(false);
                        }
                        finally
                        {
                            IsExecuting = false;
                        }
                    }

                    protected override async void Execute(object parameter)
                    {
                        await Execute().ConfigureAwait(false);
                    }

                    protected override bool CanExecute(object parameter)
                    {
                        if (IsExecuting) return false;
                        return _canExecuteMethod?.Invoke() ?? true;
                    }
                }

                /// <summary>
                /// Polyfill for <c>AsyncDelegateCommand&lt;T&gt;</c> for Prism versions prior to 9.0.
                /// </summary>
                public class AsyncDelegateCommand<T> : DelegateCommandBase
                {
                    private bool _isExecuting;
                    private readonly Func<T, Task> _executeMethod;
                    private readonly Func<T, bool>? _canExecuteMethod;

                    public AsyncDelegateCommand(Func<T, Task> executeMethod)
                        : this(executeMethod, null)
                    {
                    }

                    public AsyncDelegateCommand(Func<T, Task> executeMethod, Func<T, bool>? canExecuteMethod)
                    {
                        _executeMethod = executeMethod ?? throw new ArgumentNullException(nameof(executeMethod));
                        _canExecuteMethod = canExecuteMethod;
                    }

                    public bool IsExecuting
                    {
                        get => _isExecuting;
                        private set
                        {
                            _isExecuting = value;
                            RaiseCanExecuteChanged();
                        }
                    }

                    public async Task Execute(T parameter)
                    {
                        if (IsExecuting) return;
                        try
                        {
                            IsExecuting = true;
                            await _executeMethod(parameter).ConfigureAwait(false);
                        }
                        finally
                        {
                            IsExecuting = false;
                        }
                    }

                    protected override async void Execute(object parameter)
                    {
                        await Execute((T)parameter!).ConfigureAwait(false);
                    }

                    protected override bool CanExecute(object parameter)
                    {
                        if (IsExecuting) return false;
                        return _canExecuteMethod?.Invoke((T)parameter!) ?? true;
                    }
                }
            }
            """;
    }
}
