using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Prism.SourceGenerators.Diagnostics;
using Prism.SourceGenerators.Helpers;
using Prism.SourceGenerators.Models;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Prism.SourceGenerators;

/// <summary>
/// A source generator that generates observable properties for classes inheriting from <c>Prism.Mvvm.BindableBase</c>.
/// Fields annotated with <c>[ObservableProperty]</c> will have corresponding public properties generated
/// that call <c>SetProperty</c> in the setter.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ObservablePropertyGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("ObservablePropertyAttribute.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace Prism.SourceGenerators;

                /// <summary>
                /// An attribute that can be applied to a field in a class inheriting from
                /// <c>Prism.Mvvm.BindableBase</c> to generate an observable property that
                /// calls <c>SetProperty</c> in the setter.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
                [global::System.Diagnostics.Conditional("PRISM_SOURCEGENERATORS_ATTRIBUTES")]
                internal sealed class ObservablePropertyAttribute : global::System.Attribute
                {
                }
                """);
        });

        IncrementalValuesProvider<Result<PropertyGenerationInfo>> propertyInfos =
            context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "Prism.SourceGenerators.ObservablePropertyAttribute",
                    static (node, _) => node is VariableDeclaratorSyntax
                    {
                        Parent: VariableDeclarationSyntax
                        {
                            Parent: FieldDeclarationSyntax
                            {
                                Parent: ClassDeclarationSyntax or RecordDeclarationSyntax
                            }
                        }
                    },
                    static (context, token) =>
                    {
                        IFieldSymbol fieldSymbol = (IFieldSymbol)context.TargetSymbol;
                        INamedTypeSymbol containingType = fieldSymbol.ContainingType;

                        bool isPartial = containingType.DeclaringSyntaxReferences
                            .Select(r => r.GetSyntax(token))
                            .OfType<TypeDeclarationSyntax>()
                            .Any(static t => t.Modifiers.Any(SyntaxKind.PartialKeyword));

                        if (!isPartial)
                        {
                            return new Result<PropertyGenerationInfo>(
                                default!,
                                ImmutableArray.Create(
                                    DiagnosticInfo.Create(
                                        DiagnosticDescriptors.NonPartialClassWithObservableProperty,
                                        containingType,
                                        containingType.Name)));
                        }

                        string fieldName = fieldSymbol.Name;
                        string propertyName = GetPropertyName(fieldName);
                        string fieldType = fieldSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        HierarchyInfo hierarchy = HierarchyInfo.From(containingType);

                        return new Result<PropertyGenerationInfo>(
                            new PropertyGenerationInfo(hierarchy, fieldName, propertyName, fieldType),
                            ImmutableArray<DiagnosticInfo>.Empty);
                    });

        // Report diagnostics
        context.RegisterSourceOutput(
            propertyInfos
                .Where(static item => !item.Errors.IsEmpty),
            static (context, result) =>
            {
                foreach (DiagnosticInfo diagnostic in result.Errors.AsImmutableArray())
                {
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());
                }
            });

        // Generate source for valid items
        context.RegisterSourceOutput(
            propertyInfos
                .Where(static item => item.Value is not null && item.Errors.IsEmpty)
                .Select(static (item, _) => item.Value!),
            static (context, info) =>
            {
                CompilationUnitSyntax compilationUnit = info.Hierarchy.GetCompilationUnit(
                    ImmutableArray.Create<MemberDeclarationSyntax>(
                        PropertyDeclaration(
                            IdentifierName(info.FieldType),
                            Identifier(info.PropertyName))
                        .AddModifiers(Token(SyntaxKind.PublicKeyword))
                        .AddAccessorListAccessors(
                            AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                                .WithExpressionBody(ArrowExpressionClause(IdentifierName(info.FieldName)))
                                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                            AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                                .WithExpressionBody(ArrowExpressionClause(
                                    InvocationExpression(IdentifierName("SetProperty"))
                                        .AddArgumentListArguments(
                                            Argument(IdentifierName(info.FieldName))
                                                .WithRefKindKeyword(Token(SyntaxKind.RefKeyword)),
                                            Argument(IdentifierName("value")))))
                                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))));

                context.AddSource(
                    $"{info.Hierarchy.FilenameHint}.{info.PropertyName}.g.cs",
                    compilationUnit.GetText(System.Text.Encoding.UTF8));
            });
    }

    private static string GetPropertyName(string fieldName)
    {
        if (fieldName.StartsWith("m_") && fieldName.Length > 2)
            return char.ToUpperInvariant(fieldName[2]) + fieldName.Substring(3);
        if (fieldName.StartsWith("_") && fieldName.Length > 1)
            return char.ToUpperInvariant(fieldName[1]) + fieldName.Substring(2);
        return char.ToUpperInvariant(fieldName[0]) + fieldName.Substring(1);
    }
}
