namespace Prism.SourceGenerators;

/// <summary>
/// Declared accessibility for the property generated by <see cref="ObservablePropertyAttribute"/> when the
/// attribute is applied to a <b>backing field</b> (field target mode). Partial property targets use the
/// accessibility written on the property declaration instead.
/// </summary>
public enum ObservablePropertyAccess
{
    /// <summary>Generated property is <c>public</c>. This is the default.</summary>
    Public = 0,

    /// <summary>Generated property is <c>internal</c>.</summary>
    Internal = 1,

    /// <summary>Generated property is <c>protected</c>.</summary>
    Protected = 2,

    /// <summary>Generated property is <c>private</c>.</summary>
    Private = 3,

    /// <summary>Generated property is <c>protected internal</c>.</summary>
    ProtectedInternal = 4,

    /// <summary>Generated property is <c>private protected</c>.</summary>
    PrivateProtected = 5,
}
